[package]
name = "fractal_viewer"
version = "0.3.3"
edition = "2021"
description = "Cross-platform GPU-accelerated viewer for the Mandelbrot set and related fractals"
repository = "https://github.com/arthomnix/fractal_viewer"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1"
winit = "0.27"
env_logger = "0.9"
log = "0.4"
wgpu = "0.14"
naga = "0.10"
pollster = "0.2"
bytemuck = { version = "1.12", features = [ "derive" ] }
egui = "0.19"
egui_wgpu_backend = "0.20"
instant = "0.1"
bincode = "1.3"
serde = { version = "1.0", features = [ "derive" ] }
base64 = "0.13"
url = "2.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.1"
egui-winit = "0.19"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
wgpu = { version = "0.14", features = [ "webgl" ] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [ "Document", "Window", "Element", "Clipboard", "Navigator", "Location" ] }
getrandom = { version = "0.2.7", features = [ "js" ] }
egui-winit = { version = "0.19", default-features = false }